"""ESP32 Provisioning - Generate ESP32 connection config."""

from typing import Dict, Optional
from pathlib import Path
import json


class ESP32Provisioning:
    """Generate ESP32 connection configuration."""

    def __init__(self, broker_ip: str = "localhost", broker_port: int = 1883):
        self.broker_ip = broker_ip
        self.broker_port = broker_port

    def generate_config(self, device_id: str, username: str, password: str,
                        topic_prefix: str = "nyamuk") -> Dict[str, str]:
        """Generate ESP32 configuration."""
        return {
            "MQTT_SERVER": f'"{self.broker_ip}"',
            "MQTT_PORT": str(self.broker_port),
            "MQTT_USER": f'"{username}"',
            "MQTT_PASSWORD": f'"{password}"',
            "DEVICE_ID": f'"{device_id}"',
            "TOPIC_PREFIX": f'"{topic_prefix}"',
            "TOPIC_SENSOR": f'"{topic_prefix}/{device_id}/sensor"',
            "TOPIC_COMMAND": f'"{topic_prefix}/{device_id}/command"',
            "TOPIC_STATUS": f'"{topic_prefix}/{device_id}/status"',
        }

    def generate_arduino_snippet(self, device_id: str, username: str, 
                                  password: str, topic_prefix: str = "nyamuk") -> str:
        """Generate Arduino code snippet."""
        config = self.generate_config(device_id, username, password, topic_prefix)
        
        snippet = f"""// Nyamuk ESP32 Configuration
// Generated by Nyamuk MQTT Broker

// WiFi Settings
const char* WIFI_SSID = "YOUR_WIFI_SSID";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";

// MQTT Settings
const char* MQTT_SERVER = {config['MQTT_SERVER']};
const int MQTT_PORT = {config['MQTT_PORT']};
const char* MQTT_USER = {config['MQTT_USER']};
const char* MQTT_PASSWORD = {config['MQTT_PASSWORD']};

// Device ID
const char* DEVICE_ID = {config['DEVICE_ID']};

// Topics
const char* TOPIC_SENSOR = {config['TOPIC_SENSOR']};
const char* TOPIC_COMMAND = {config['TOPIC_COMMAND']};
const char* TOPIC_STATUS = {config['TOPIC_STATUS']};
"""
        return snippet

    def generate_full_arduino(self, device_id: str, username: str,
                               password: str, topic_prefix: str = "nyamuk",
                               sensor_type: str = "basic") -> str:
        """Generate complete Arduino sketch."""
        config = self.generate_config(device_id, username, password, topic_prefix)
        
        if sensor_type == "dht22":
            return self._generate_dht22_sketch(config)
        elif sensor_type == "bmp280":
            return self._generate_bmp280_sketch(config)
        else:
            return self._generate_basic_sketch(config)

    def _generate_basic_sketch(self, config: dict) -> str:
        return f"""/*
 * Nyamuk ESP32 Basic Sketch
 * Generated by Nyamuk MQTT Broker
 */

#include <WiFi.h>
#include <PubSubClient.h>
#include <ArduinoJson.h>

// WiFi
const char* WIFI_SSID = "YOUR_WIFI_SSID";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";

// MQTT
const char* MQTT_SERVER = {config['MQTT_SERVER']};
const int MQTT_PORT = {config['MQTT_PORT']};
const char* MQTT_USER = {config['MQTT_USER']};
const char* MQTT_PASSWORD = {config['MQTT_PASSWORD']};
const char* DEVICE_ID = {config['DEVICE_ID']};

// Topics
const char* TOPIC_SENSOR = {config['TOPIC_SENSOR']};
const char* TOPIC_COMMAND = {config['TOPIC_COMMAND']};
const char* TOPIC_STATUS = {config['TOPIC_STATUS']};

WiFiClient espClient;
PubSubClient client(espClient);

void setup() {{
    Serial.begin(115200);
    connectWiFi();
    client.setServer(MQTT_SERVER, MQTT_PORT);
    connectMQTT();
}}

void loop() {{
    if (!client.connected()) connectMQTT();
    client.loop();
    
    // Publish sensor data every 5 seconds
    static unsigned long lastSend = 0;
    if (millis() - lastSend > 5000) {{
        publishSensorData();
        lastSend = millis();
    }}
}}

void connectWiFi() {{
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    while (WiFi.status() != WL_CONNECTED) delay(500);
    Serial.println("WiFi connected");
}}

void connectMQTT() {{
    while (!client.connected()) {{
        if (client.connect(DEVICE_ID, MQTT_USER, MQTT_PASSWORD)) {{
            client.subscribe(TOPIC_COMMAND);
            client.publish(TOPIC_STATUS, "online", true);
        }} else delay(5000);
    }}
}}

void publishSensorData() {{
    StaticJsonDocument<256> doc;
    doc["device_id"] = DEVICE_ID;
    doc["temperature"] = 25.0 + random(-50, 50) / 10.0;
    doc["humidity"] = 60.0 + random(-100, 100) / 10.0;
    
    char buffer[256];
    serializeJson(doc, buffer);
    client.publish(TOPIC_SENSOR, buffer);
}}
"""

    def _generate_dht22_sketch(self, config: dict) -> str:
        return f"""/*
 * Nyamuk ESP32 DHT22 Sketch
 * Generated by Nyamuk MQTT Broker
 */

#include <WiFi.h>
#include <PubSubClient.h>
#include <ArduinoJson.h>
#include <DHT.h>

// WiFi
const char* WIFI_SSID = "YOUR_WIFI_SSID";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";

// MQTT
const char* MQTT_SERVER = {config['MQTT_SERVER']};
const int MQTT_PORT = {config['MQTT_PORT']};
const char* MQTT_USER = {config['MQTT_USER']};
const char* MQTT_PASSWORD = {config['MQTT_PASSWORD']};
const char* DEVICE_ID = {config['DEVICE_ID']};

// Topics
const char* TOPIC_SENSOR = {config['TOPIC_SENSOR']};
const char* TOPIC_COMMAND = {config['TOPIC_COMMAND']};
const char* TOPIC_STATUS = {config['TOPIC_STATUS']};

// DHT22
#define DHTPIN 4
#define DHTTYPE DHT22
DHT dht(DHTPIN, DHTTYPE);

WiFiClient espClient;
PubSubClient client(espClient);

void setup() {{
    Serial.begin(115200);
    dht.begin();
    connectWiFi();
    client.setServer(MQTT_SERVER, MQTT_PORT);
    connectMQTT();
}}

void loop() {{
    if (!client.connected()) connectMQTT();
    client.loop();
    
    static unsigned long lastSend = 0;
    if (millis() - lastSend > 10000) {{
        publishDHT22Data();
        lastSend = millis();
    }}
}}

void connectWiFi() {{
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    while (WiFi.status() != WL_CONNECTED) delay(500);
}}

void connectMQTT() {{
    while (!client.connected()) {{
        if (client.connect(DEVICE_ID, MQTT_USER, MQTT_PASSWORD)) {{
            client.subscribe(TOPIC_COMMAND);
            client.publish(TOPIC_STATUS, "online", true);
        }} else delay(5000);
    }}
}}

void publishDHT22Data() {{
    float temp = dht.readTemperature();
    float hum = dht.readHumidity();
    if (isnan(temp) || isnan(hum)) return;
    
    StaticJsonDocument<256> doc;
    doc["device_id"] = DEVICE_ID;
    doc["temperature"] = round(temp * 10.0) / 10.0;
    doc["humidity"] = round(hum * 10.0) / 10.0;
    
    char buffer[256];
    serializeJson(doc, buffer);
    client.publish(TOPIC_SENSOR, buffer);
}}
"""

    def _generate_bmp280_sketch(self, config: dict) -> str:
        return f"""/*
 * Nyamuk ESP32 BMP280 Sketch
 * Generated by Nyamuk MQTT Broker
 */

#include <WiFi.h>
#include <PubSubClient.h>
#include <ArduinoJson.h>
#include <Wire.h>
#include <Adafruit_BMP280.h>

// WiFi
const char* WIFI_SSID = "YOUR_WIFI_SSID";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";

// MQTT
const char* MQTT_SERVER = {config['MQTT_SERVER']};
const int MQTT_PORT = {config['MQTT_PORT']};
const char* MQTT_USER = {config['MQTT_USER']};
const char* MQTT_PASSWORD = {config['MQTT_PASSWORD']};
const char* DEVICE_ID = {config['DEVICE_ID']};

// Topics
const char* TOPIC_SENSOR = {config['TOPIC_SENSOR']};
const char* TOPIC_COMMAND = {config['TOPIC_COMMAND']};
const char* TOPIC_STATUS = {config['TOPIC_STATUS']};

// BMP280
Adafruit_BMP280 bmp;

WiFiClient espClient;
PubSubClient client(espClient);

void setup() {{
    Serial.begin(115200);
    Wire.begin();
    bmp.begin(0x76);
    connectWiFi();
    client.setServer(MQTT_SERVER, MQTT_PORT);
    connectMQTT();
}}

void loop() {{
    if (!client.connected()) connectMQTT();
    client.loop();
    
    static unsigned long lastSend = 0;
    if (millis() - lastSend > 15000) {{
        publishBMP280Data();
        lastSend = millis();
    }}
}}

void connectWiFi() {{
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    while (WiFi.status() != WL_CONNECTED) delay(500);
}}

void connectMQTT() {{
    while (!client.connected()) {{
        if (client.connect(DEVICE_ID, MQTT_USER, MQTT_PASSWORD)) {{
            client.subscribe(TOPIC_COMMAND);
            client.publish(TOPIC_STATUS, "online", true);
        }} else delay(5000);
    }}
}}

void publishBMP280Data() {{
    StaticJsonDocument<256> doc;
    doc["device_id"] = DEVICE_ID;
    doc["temperature"] = round(bmp.readTemperature() * 100.0) / 100.0;
    doc["pressure"] = round(bmp.readPressure() / 100.0 * 100.0) / 100.0;
    doc["altitude"] = round(bmp.readAltitude(1013.25) * 100.0) / 100.0;
    
    char buffer[256];
    serializeJson(doc, buffer);
    client.publish(TOPIC_SENSOR, buffer);
}}
"""
